---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: enterprisecontracts.appstudio.redhat.com
spec:
  group: appstudio.redhat.com
  names:
    kind: EnterpriseContract
    listKind: EnterpriseContractList
    plural: enterprisecontracts
    shortNames:
      - ec
    singular: enterprisecontract
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: EnterpriseContract JSON Schema
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: EnterpriseContractSpec defines the enforced EnterpriseContract
              properties:
                rules:
                  description: Enforced rules
                  items:
                    description: Rule to asser
                    properties:
                      ref:
                        description: Reference to the stored policy rules
                        type: string
                      suppress:
                        description: List of rules by name to suppress
                        items:
                          type: string
                        type: array
                    required:
                      - ref
                    type: object
                  type: array
              required:
                - rules
              type: object
            status:
              description: Current status of the EnterpriseContract
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
