---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec-reader
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - enterprisecontracts
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ec-read-demo-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ec-reader
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: demo
